apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bidding
  template:
    metadata:
      labels:
        app: bidding
    spec:
      containers:
        - name: bidding
          image: ranandan10/auction-website-bid
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: auction
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: BID_MYSQL_URI
              value: 'mysql://bidding-mysql-service:8080/bid'
---
apiVersion: v1
kind: Service
metadata:
  name: bidding-service
spec:
  selector:
    app: bidding
  ports:
    - name: bidding
      protocol: TCP
      port: 3000
      targetPort: 3000
